### ISSUE TITLE
Service Worker Seems to Inactivate and Not Reactivativate 

### ISSUE THREAD

**Issue by ekuller** [privacy-tech-lab/gpc-privacy-choice#181]
Service worker (background.js)  functionality stops working after the extension has been activated for a period.

**Comment by chunyuema** [comment]
Unfortunately, I was able to replicate the issue today. I will focus on solving this issue as a priority.

**Comment by chunyuema** [comment]
This should not affect the testing of our extension.

**Comment by chunyuema** [comment]
I was unable to replicate the same issue after last time it occurred. It seems to be a problem that many people encounter based on the forum posts I read. However, I am hoping that this issue is not very relevant for us as it occurs rarely. Theoretically, when content script sends some messages to the service worker, it should wake up from the inactive state and deal with it. 

Just in case that the issue still persists, I will add this method to [keep the service worker awake](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/LQ_VpMCpksw/m/-gi2tTFrBAAJ). The trick is to have some function that sends messages to service worker once in a while such that it never falls asleep. It should solve our problem.
